kind: Namespace
apiVersion: v1
metadata:
  name: web-dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: api-dev
---
apiVersion: v1
kind: Secret
metadata:
  namespace: api-dev
  name: sql-data
data:
  # echo -n 'mysecretpassword' | base64
  SQL_USER: bGl4bw==
  SQL_PASSWORD: bGl4bw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  api-dev
  name: user-java-deployment
  labels:
    app: user-java
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryylk9728.azurecr.io/user-java:latest
        env:
        - name: SQL_SERVER
          value: "sqlserverylk9728.database.windows.net"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_PASSWORD
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#         limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: api-dev
  name: user-java-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-java

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  api-dev
  name: poi-deployment
  labels:
    app: poi
spec:
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryylk9728.azurecr.io/poi:latest
        env:
        - name: SQL_SERVER
          value: "sqlserverylk9728.database.windows.net"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_PASSWORD
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#         limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace:  api-dev
  name: poi-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace:  api-dev
  name: user-profile-deployment
  labels:
    app: user-profile
spec:
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registryylk9728.azurecr.io/userprofile:latest
        env:
        - name: SQL_SERVER
          value: "sqlserverylk9728.database.windows.net"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_PASSWORD
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#         limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: api-dev
  name: user-profile-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: user-profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api-dev
  name: trips-deployment
  labels:
    app: trips
spec:
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryylk9728.azurecr.io/trips:latest
        env:
        - name: SQL_SERVER
          value: "sqlserverylk9728.database.windows.net"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: SQL_PASSWORD
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#         limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: api-dev
  name: trips-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: trips

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-dev
  name: trip-viewer-deployment
  labels:
    app: trip-viewer
spec:
  selector:
    matchLabels:
      app: trip-viewer
  template:
    metadata:
      labels:
        app: trip-viewer
    spec:
      containers:
      - name: trip-viewer
        image: registryylk9728.azurecr.io/tripviewer:latest
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.api-dev.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://user-profile-service.api-dev.svc.cluster.local"
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#         limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: web-dev
  name: trip-viewer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: trip-viewer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-role
  namespace: web-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-group-access
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-role
subjects:
- kind: Group
  namespace: web-dev
  name: ce966c67-8b78-4f51-a611-7c54da0fbf14 # AZ Directory Group: AKS Web Devs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-role
  namespace: api-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-group-access
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-role
subjects:
- kind: Group
  namespace: api-dev
  name: 547ea1b8-e988-4223-a015-7711894d0966 # AZ Directory Group: AKS Api Devs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /api/poi
        pathType: Prefix
        backend:
          service:
            name: poi-service
            port:
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service:
            name: trips-service
            port:
              number: 80
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user-profile-service
            port:
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: user-java-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: trip-viewer-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trip-viewer-service
            port:
              number: 80
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api-dev
spec:
  provider: azure
  secretObjects:
    - data:
      - key: SQL_PASSWORD
        objectName: SQL_PASSWORD
      - key: SQL_USER
        objectName: SQL_USER
      secretName: "kv-secrets"
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "1663996e-8ec9-48ec-9fee-cdc6dfb12d7d"
    keyvaultName: "tripinsightskv"
    objects: |
      array:
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
    tenantId: "4bf5b635-285a-4966-83bd-6ee1ec7e7913"
    
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-dev-policy
  namespace: web-dev
spec:
  podSelector:
    matchLabels:
      app: trip-viewer
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: api-dev
    ports:
      - protocol: TCP
        port: 80
  - to:
    ports:
      - protocol: UDP
        port: 53

